### ISSUE TITLE
Compile problem on windows.

### ISSUE THREAD

**Issue by dearn44** [ashish157/QtKnobs#2]
I did succeed to compile the library on Mac Os, yet I encountered this problem when trying the same on two separate windows machines with Qt version 5.3 and 5.4 respectively. 

Issue:
```
C:\Users\PC\Downloads\QtTestsWindows\QtKnobs-master\QtKnobs\styles\needlestyle.cpp:72: error: C2360: initialization of 'points' is skipped by 'case' label

C:\Users\PC\Downloads\QtTestsWindows\QtKnobs-master\QtKnobs\styles\needlestyle.cpp:77: error: C2360: initialization of 'points' is skipped by 'case' label
```

On a side note, it would be good to have a compilable example.

Have a nice day.

**Comment by ashish157** [comment]
Hi,

Thank you for bringing it to the notice. The problem was that Windows VC++ compiler required the case labels to be scope specific. Added parentheses for the cases. It should compile now. I had actually not tested on Windows and Mac OS yet. Another thanks for letting me know it works on Mac too :+1: 
The changes have been comitted.
An example is already provided and can be used by creating a QtQuick Application and following the steps in README. Ill still look into providing a compilable example. 

Best,
Ashish

**Comment by dearn44** [comment]
Yes I do confirm that it works fine under Mavericks. 
Thank you for the quick reply, and the fix. 

Regards,
Dearn.
